import BaseType from './BaseType';

export default class AsaasPaymentStatus extends BaseType {
  static PENDING = 'PENDING';
  static CONFIRMED = 'CONFIRMED';
  static RECEIVED = 'RECEIVED';
  static RECEIVED_IN_CASH = 'RECEIVED_IN_CASH';
  static OVERDUE = 'OVERDUE';
  static REFUND_REQUESTED = 'REFUND_REQUESTED';
  static REFUNDED = 'REFUNDED';
  static CHARGEBACK_REQUESTED = 'CHARGEBACK_REQUESTED';
  static CHARGEBACK_DISPUTE = 'CHARGEBACK_DISPUTE';
  static AWAITING_CHARGEBACK_REVERSAL = 'AWAITING_CHARGEBACK_REVERSAL';
  static DUNNING_REQUESTED = 'DUNNING_REQUESTED';
  static DUNNING_RECEIVED = 'DUNNING_RECEIVED';
  static AWAITING_RISK_ANALYSIS = 'AWAITING_RISK_ANALYSIS';
  static CANCELED = 'CANCELED';
}
