name: publish ikomida dev lib to artifact registry on push
on:
  push:
    branches:
      - dev
jobs:
  build_and_deploy_ikomida:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.ARTIFACT_REGISTRY_IKOMIDA_DEV_SERVICE_ACOUNT }}"
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
          cache: yarn
      - id: publish
        run: |
          # gcloud auth activate-service-account artifact-registry@ikomida-dev.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          rm .npmrc || true
          echo "ok"
          echo "@ikomida:registry=https://us-central1-npm.pkg.dev/ikomida-dev/node/" >> .npmrc && echo "//us-central1-npm.pkg.dev/ikomida-dev/node/:always-auth=true" >> .npmrc
          echo "ok"
          node --version
          echo "ok"
          npx google-artifactregistry-auth
          echo "ok"
          yarn install --frozen-lockfile
          npm publish
