name: build and test ikomida dev lib before pull request merge
on:
  pull_request:
    branches:
      - dev
      - hmlg
      - main
jobs:
  build_ikomida:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ endsWith(github.ref, '/main') && secrets.ARTIFACT_REGISTRY_IKOMIDA_PROD_SERVICE_ACOUNT || (endsWith(github.ref, '/hmlg') && secrets.ARTIFACT_REGISTRY_IKOMIDA_HMLG_SERVICE_ACOUNT || secrets.ARTIFACT_REGISTRY_IKOMIDA_DEV_SERVICE_ACOUNT) }}"
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
          cache: yarn
      - name: Auth npm with artifactregistry and set gcloud project id
        env:
          PROJECT_ID: ${{ steps.auth.outputs.project_id }}
        run: |
          echo "Selected gcloud project id: ${PROJECT_ID}"
          rm .npmrc || true
          echo "@ikomida:registry=https://us-central1-npm.pkg.dev/${PROJECT_ID}/node/" >> .npmrc
          echo "//us-central1-npm.pkg.dev/${PROJECT_ID}/node/:always-auth=true" >> .npmrc
          yarn glogin
      - name: Check lib version
        run: |
          LIB_NAME=$(node --eval="process.stdout.write(require('./package.json').name)")
          LIB_VERSION=$(node --eval="process.stdout.write(require('./package.json').version)")
          LIB_VERSION_REMOTE=$(npm view "${LIB_NAME}" version)
          if [[ $LIB_VERSION > $LIB_VERSION_REMOTE ]]; then
            echo "Lib package version is correct"
            exit 0
          else 
            echo "Error: you mast update lib package version"
            exit 1
          fi
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Prepare code
        run: |
          yarn format
          yarn lint
      - name: Build code
        run: yarn build
