name: build and test ikomida prod lib before pull request merge
on:
  pull_request:
    branches:
      - prod
jobs:
  build_ikomida:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.ARTIFACT_REGISTRY_IKOMIDA_DEV_SERVICE_ACOUNT }}"
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
          cache: yarn
      - name: Auth npm with artifactregistry
        run: |
          rm .npmrc || true
          echo "@ikomida:registry=https://us-central1-npm.pkg.dev/ikomida-prod/node/" >> .npmrc
          echo "//us-central1-npm.pkg.dev/ikomida-prod/node/:always-auth=true" >> .npmrc
          yarn glogin
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: check lib version
        run: |
          LIB_NAME=$(node --eval="process.stdout.write(require('./package.json').name)")
          LIB_VERSION=$(node --eval="process.stdout.write(require('./package.json').version)")
          LIB_VERSION_REMOTE=$(npm view @ikomida/shared-types version)
          l=$(printf '%s\n%s\n' "$monterey" "$LIB_VERSION_REMOTE" | sort -V | tail -n1)
          if [[ $LIB_VERSION > $l ]]; then
            echo "Lib package version is correct"
            exit 0
          else 
            echo "Error: you mast update lib package version"
            exit 1
          fi
